# This is a config for E2B sandbox template.
# You can use template ID (je1rwz33jaleqyutp73w) or template name (wibe-nextjs-test-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("wibe-nextjs-test-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("wibe-nextjs-test-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('wibe-nextjs-test-2')

team_id = "567e369a-59dc-4ec6-92cc-079b2ee06d57"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "wibe-nextjs-test-2"
template_id = "je1rwz33jaleqyutp73w"
